#!/bin/bash

echo "🔧 Jenkins Post-Installation Configuration Script"
echo "=================================================="

echo ""
echo "📋 AFTER Jenkins web setup is complete, run these steps:"
echo ""
echo "1. INSTALL ADDITIONAL PLUGINS:"
echo "   Go to: Manage Jenkins → Plugins → Available"
echo "   Search and install:"
echo "   - Docker Pipeline"
echo "   - Kubernetes"
echo "   - Pipeline: AWS Steps"
echo "   - SonarQube Scanner"
echo ""
echo "2. CONFIGURE TOOLS:"
echo "   Manage Jenkins → Tools"
echo "   Add:"
echo "   - JDK 17 (name: jdk17)"
echo "   - Node.js 18 (name: node18)"
echo "   - Docker (ensure Docker is installed)"
echo ""
echo "3. SET UP CREDENTIALS:"
echo "   Manage Jenkins → Credentials → System → Global credentials"
echo "   Add:"
echo "   - Kind: Username with password"
echo "   - ID: github-cred"
echo "   - Username/Password: Your GitHub credentials"
echo ""
echo "4. CREATE PIPELINE JOB:"
echo "   New Item → Enter name: 'bookmyshow-pipeline'"
echo "   Select: Pipeline"
echo "   In Pipeline section:"
echo "   - Definition: Pipeline script from SCM"
echo "   - SCM: Git"
echo "   - Repository URL: https://github.com/staragile2016/Book-My-Show.git"
echo "   - Credentials: Select your github-cred"
echo "   - Script Path: Jenkinsfile"
echo "   - Save"
echo ""
echo "5. RUN FIRST BUILD:"
echo "   Click 'Build Now' on pipeline job"
echo ""
echo "✅ Done! Pipeline will build, test, and deploy BookMyShow application."
